export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';// 设置登录状态
export const SET_CONTEXT_DATA = 'SET_CONTEXT_DATA';// 设置上下文
export const SET_MENUS = 'SET_MENUS';// 设置菜单
export const SET_MENUS_MAP = 'SET_MENUS_MAP';// 设置菜单映射
export const SET_CUR_MENU = 'SET_CUR_MENU';// 设置当前菜单
export const SET_CODE_MENUS_MAP = 'SET_CODE_MENUS_MAP';// 设置菜单code到菜单对象的映射
export const SET_ROUTER_MAP = 'SET_ROUTER_MAP';// 设置路由映射
export const SET_PREVIOUS_ROUTER = 'SET_PREVIOUS_ROUTER';// 设置前一个路由
export const SET_CUR_ROUTER = 'SET_CUR_ROUTER';// 设置当前路由
export const REFRESH_MSG_TIP = 'REFRESH_MSG_TIP'; // 消息提示
export const SET_MOBILENAV = 'SET_MOBILENAV'; // 消息提示
